# Site settings
title: Praxis Network Directories
email: scholarslab@virginia.edu
description: "placeholder for short description"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
category_dir:
