# Site settings
title: The Real Slim Shady
email: marshall@mathers.com
description: "Allied Rappers of D-12 baby"
baseurl: ""
url: "http://yourdomain.com"
collections:
  institutions:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
exclude: ["README.md", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE", "bower.json"
category_dir:
