# Site settings
title: The Real Slim Shady
email: marshall@mathers.com
description: "Allied Rappers of D-12 baby"
baseurl: ""
url: "http://yourdomain.com"
permalink: /:categories/:title

# Build settings
markdown: kramdown
permalink: pretty
